- id: kabamdam
  name: kabamdam
  description: Update project status heatmap and README links based on Roadmap and Timesheet changes.
  entry: kabamdam
  language: python
  files: ^(docs/roadmap/ROADMAP\.md|timesheets\.md)$
  pass_filenames: false
